language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - gem install bundler -v '= 1.13.1'
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database easylanguages_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
script:
  - bundle exec rspec spec

